apiVersion: v1
kind: Service
metadata:
  name: nginx-app-service
  labels:
    run: nginx-app-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30081
    protocol: TCP
  selector:
    run: nginx-app
